### ISSUE TITLE
Timer to Time Rift 1min beyond

### ISSUE THREAD

**Issue by mrlinuxdude** [TomCats/TomCats-WoW-AddOns#2]
I watch your streams on twitch thanks for your addon support. TomCats Tours

Timer to the Time Rift was 1 min  beyond just want to make you aware if you didn't already know

**Comment by TomCats** [comment]
Yep, already aware.  I'm just basing it on the server time as the widget info isn't always available to the player.  When it is available, the date is coming in pre-formatted and in a place in the tooltip I'd rather not risk the perils of different localizations, a decision by Blizzard to move it to another row, etc., so as getting this more precisely in sync is of little value to players I've moved on with the compromise.  Plenty of other more valuable features to work on with that time!

**Comment by mrlinuxdude** [comment]
Thank you. Awesome
